#!/bin/bash
set -euo pipefail

PRODUCT=$(sed -n 's/.*AssemblyProduct("\([^"]*\)")]/\1/p' ./SolutionInfo.cs)
VERSION=$(sed -n 's/.*AssemblyInformationalVersion("\([^"]*\)")]/\1/p' ./SolutionInfo.cs)
OUTPUT_DIR=./build

GREEN=$(tput setaf 2)
RESET=$(tput sgr0)

function say {
  echo -e "${GREEN}$1${RESET}"
}

function build_solution {
  say "Building $PRODUCT v$VERSION..."
  xbuild /p:Configuration=Release Resilient.Net.sln
}

function package_nuspec {
  say "Packing nuspec..."
  mkdir -p $OUTPUT_DIR
  nuget pack Resilient.Net.nuspec -Version $VERSION -OutputDirectory $OUTPUT_DIR
}

function push_package {
  api_key="${NUGET_API_KEY:?NuGet API key not defined}"
  say "Publishing $PRODUCT v$VERSION to NuGet..."
  nuget push $OUTPUT_DIR/resilient.net.*.nupkg $api_key
}

build_solution
package_nuspec
push_package
